services:
  - type: web
    name: x-optimus-userbot
    env: python
    region: oregon
    plan: free
    buildCommand: |
      sudo bash render-build.sh
      pip install -r requirements.txt
    startCommand: "python main.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: OWNER
        sync: false
